In [ ]:
import pandas as pd

    # Load data from Order.csv
df = pd.read_csv('Order.csv')

In [8]:
#df.head()
#df.tail()
#df.info()
#df.describe()
#df.index
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [ ]:
#Indexing and selecting data

    #indexing using column name
#df["Country"]
#len(df["Country"])
#set(df["Country"])
#df[["Country", "Product", "Price"]]

    #indexing using row number
    #iloc = index location
#df.iloc[0] 
#list(df.iloc[10])
    #selecting rows from 10 to 14
#df.iloc[10:15] 
    #selecting country column for row 10
#df.iloc[10]["Country"]
    #selecting rows from 10 to 11 and columns from 0 to 2 
df.iloc[10:12, 0:3]

    OrderID CustomerName Product
10     1011  Liam Harris   Phone
11     1012   Mia Martin      TV

In [ ]:
    #selecting rows where category is Electronics
#df[df["Category"]== 'Electronics']
    #selecting rows where category is Electronics and price is greater than 1000
df[(df["Category"]== 'Electronics') & (df["Price"] > 1000)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200,2024-01-05,Yes,USA
11,1012,Mia Martin,TV,Electronics,1,1100,2024-01-16,No,Italy

In [ ]:
    #selecting rows where category is Electronics or price is greater than 1000
df[(df["Category"]== 'Electronics') | (df["Price"] > 1000)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200,2024-01-05,Yes,USA
1,1002,Emma Brown,Headphones,Electronics,2,150,2024-01-06,Yes,UK
4,1005,Daniel Wilson,Mouse,Electronics,3,25,2024-01-09,Yes,Spain
5,1006,Olivia Taylor,Keyboard,Electronics,2,70,2024-01-10,No,Italy
6,1007,James Anderson,Monitor,Electronics,1,400,2024-01-11,Yes,USA
7,1008,Isabella Thomas,Tablet,Electronics,2,350,2024-01-12,Yes,UK
10,1011,Liam Harris,Phone,Electronics,1,900,2024-01-15,Yes,Spain
11,1012,Mia Martin,TV,Electronics,1,1100,2024-01-16,No,Italy
12,1013,Noah Thompson,Camera,Electronics,1,600,2024-01-17,Yes,USA
13,1014,Charlotte Garcia,Printer,Electronics,2,250,2024-01-18,Yes,UK
16,1017,Lucas Clark,Router,Electronics,2,90,2024-01-21,Yes,Spain
17,1018,Harper Rodriguez,Scanner,Electronics,1,220,2024-01-22,No,Italy

In [ ]:
#base filtering
    #selecting rows where quantity is greater than 3
df[df['Quantity'] > 3]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Sophia Davis,Chair,Furniture,4,120,2024-01-08,Yes,France
18,1019,Mason Lewis,Chair,Furniture,5,100,2024-01-23,Yes,USA

In [ ]:
    #Advance filtering
#df[df["CustomerName"].str.endswith("a")]
    #selecting rows where country is USA or Spain
df[df["Country"].isin(["USA", "Spain"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200,2024-01-05,Yes,USA
4,1005,Daniel Wilson,Mouse,Electronics,3,25,2024-01-09,Yes,Spain
6,1007,James Anderson,Monitor,Electronics,1,400,2024-01-11,Yes,USA
10,1011,Liam Harris,Phone,Electronics,1,900,2024-01-15,Yes,Spain
12,1013,Noah Thompson,Camera,Electronics,1,600,2024-01-17,Yes,USA
16,1017,Lucas Clark,Router,Electronics,2,90,2024-01-21,Yes,Spain
18,1019,Mason Lewis,Chair,Furniture,5,100,2024-01-23,Yes,USA

In [ ]:
#Updating Data
    #updating product for Mason Lewis
df.loc[df["CustomerName"] == "Mason Lewis", "Product"] = "Smartphone"
    #checking if the update was successful
df[df["CustomerName"] == "Mason Lewis"]
    #updating country name from USA to United States
df.loc[df["Country"]== "USA", "Country"] = "United States"
    #checking if the update was successful
df[df["Country"]== "United States"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200,2024-01-05,Yes,United States
6,1007,James Anderson,Monitor,Electronics,1,400,2024-01-11,Yes,United States
12,1013,Noah Thompson,Camera,Electronics,1,600,2024-01-17,Yes,United States
18,1019,Mason Lewis,Smartphone,Furniture,5,100,2024-01-23,Yes,United States

In [ ]:
    #converting country names to uppercase
df["Country"] = df["Country"].str.upper()
    #checking if the update was successful
#df["Country"]

In [ ]:
    #dropping row with index 3
df = df.drop(3)
    #dropping Price column
#df = df.drop(columns=["Price"])

In [18]:
    #dropping rows with missing values
df.dropna()
    #filling missing values in OrderID column with 0
df.fillna({"OrderID": 0}, inplace=True)

,Order ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200,2024-01-05,Yes,USA
1,1002,Emma Brown,Headphones,Electronics,2,150,2024-01-06,Yes,UK
2,1003,Michael Lee,Desk,Furniture,1,300,2024-01-07,No,Germany
3,1004,Sophia Davis,Chair,Furniture,4,120,2024-01-08,Yes,France
4,1005,Daniel Wilson,Mouse,Electronics,3,25,2024-01-09,Yes,Spain
5,1006,Olivia Taylor,Keyboard,Electronics,2,70,2024-01-10,No,Italy
6,1007,James Anderson,Monitor,Electronics,1,400,2024-01-11,Yes,USA
7,1008,Isabella Thomas,Tablet,Electronics,2,350,2024-01-12,Yes,UK
8,1009,William Jackson,Sofa,Furniture,1,800,2024-01-13,No,Germany
9,1010,Ava White,Bookshelf,Furniture,1,200,2024-01-14,Yes,France
10,1011,Liam Harris,Phone,Electronics,1,900,2024-01-15,Yes,Spain
11,1012,Mia Martin,TV,Electronics,1,1100,2024-01-16,No,Italy
12,1013,Noah Thompson,Camera,Electronics,1,600,2024-01-17,Yes,USA
13,1014,Charlotte Garcia,Printer,Electronics,2,250,2024-01-18,Yes,UK
14,1015,Ethan Martinez,Table,Furniture,1,350,2024-01-19,No,Germany
15,1016,Amelia Robinson,Lamp,Furniture,3,45,2024-01-20,Yes,France
16,1017,Lucas Clark,Router,Electronics,2,90,2024-01-21,Yes,Spain
17,1018,Harper Rodriguez,Scanner,Electronics,1,220,2024-01-22,No,Italy
18,1019,Mason Lewis,Chair,Furniture,5,100,2024-01-23,Yes,USA
19,1020,Evelyn Lee,Desk,Furniture,1,320,2024-01-24,Yes,UK

In [17]:
#Rename columns
    #renaming OrderID column to Order ID
df.rename(columns={"OrderID": "Order ID"}, inplace=True)

In [ ]:
    #calculating total price for each category
df.groupby("Country")["Price"].sum() 
    #sorting data by price in descending order
df.sort_values("Price", ascending=False)

In [19]:
    #saving updated data to a new CSV file
df.to_csv("Updated_Order.csv", index=False)